### ISSUE TITLE
[Change] Ensure compatibility with new Hypixel mod regulations

### ISSUE THREAD

**Issue by ILikePlayingGames** [BiscuitDevelopment/SkyblockAddons#517]
Hypixel recently announced that they are changing their policy for disallowed mods. Features that manipulate packets will generally be disallowed in the future. The announcement is [here](https://hypixel.net/threads/update-to-disallowed-modifications-qol-modifications.4043482/page-41#post-29366168) and the clarification post is [here](https://hypixel.net/threads/regarding-the-recent-announcement-with-mods-in-skyblock.4045481/).

# To-do:
- [ ] Ask for clarification about what counts as packet manipulation
- [ ] Determine what features are disallowed
- [ ] Disable disallowed features

# Feature list
_Up to date as of v1.6.0 beta 10 5e214b12_

Allowed | Uncertain | Not Allowed
:----: | :----: | :----:
✔️  | 🟡 | ❌ 

- Magma boss warning
- Double tap to drop
- Disable ember rod on private island
- Show backpack preview
- Hide skeleton helmet bones
- Show skeleton helmet bones bar
- Hide vanilla food and armor bars
- Full inventory warning
- Magma boss timer
- Enchantment and reforge filters
- Minion can't reach block warning
- Hide players near NPCs
- Hide vanilla health bar
- Double tap to drop in other games
- Minion full warning
- Ignore item frame clicks
- Use vanilla defence texture
- Show backpack preview only while holding shift
- Mana bar
- Mana text
- Health bar
- Health text
- Defence icon
- Defence text
- Defence percentage
- Show health updates
- Hide players in village
- Dark auction timer
- Item pickup log
- Avoid placing enchanted items
- Avoid breaking stems
- Show dark auction timer in other games
- Show item anvil uses
- Prevent movement on death
- Show magma boss timer in other games
- Don't reset cursor between inventories
- Lock slots
- Summoning eye alert
- Make enderchests green in the end
- Stop dropping and selling rare items
- Make backpack inventories coloured
- Replace roman numerals with numbers
- Change health bar colours for poison and wither
- Crafting patterns
- Fishing sound indicator
- Fix blinking night vision
- Disable minion location not perfect warning
- Jungle axe cooldown
- Organize enchantments
- SHow item cooldowns
- Skill display
- Speed percentage
- Only mine ores in deep caverns
- Slayer armor progress display
- Special zealot alert
- Only mine valuables in the nether
- Enable error message when mining non-ores in deep caverns
- Enable error message when breaking stems
- Enable error messages when mining non-valuables in nether
- Hide pet health bar
- Disable magical soup messages
- Power orb display
- Zealot counter
- Sword ticker display
- Tab list effect timers
- No arrows left alert
- Hide night vision timer
- Cake bag preview
- Repeating full inventory warning
- Sort tab list effect timers
- Show broken dragon fragments
- SBA button in pause menu
- Show total zealot count
- Show summoning eye count
- Show average zealots per eye
- Turn bow green when using toxic arrow poison
- Birch park rain timer
- Discord RPC
- Endstone protector display
- Fancy warp menu
- Double warp
- Hide grey enchantments
- Legendary sea creature warning
- Only break logs in the park
- Slayer boss close to spawning alert
- Disable teleport pad messages
- Bait list
- Zealot counter explosive bow compatibility
- Disable enderman teleportation effect
- Change zealot colour
- Hide sven pup nametags
- Repeat slayer boss warning
- Dungeon map display
- Rotate dungeon map
- Center dungeon map rotation on player
- Zoom
- Glowing dropped items
- Glowing dungeon teammates
- Show dungeon item base stat boost percentage
- Colour base stat boost by rarity
- Show player heads on map
-

**Comment by ILikePlayingGames** [comment]
After reading the admins' clarification, it seems that they mostly want to get rid of stuff that can appear like cheating to watchdog. I think it should be ok if we ensure that our click blocking blocks the click entirely so it doesn't send any packets to the server, unless the admins are opposed to the purpose these features serve.

**Comment by ILikePlayingGames** [comment]
We've determined a list of features that may be flagged by the new rules. We will be disabling these features before Friday April 9th (beginning of the kicking period) out of an abundance of caution since we are not sure exactly what will be flagged. We will test these features throughout the kicking period to determine if they indeed will be flagged.

**Comment by ILikePlayingGames** [comment]
# Disable list change log
_Log of features added/removed from the disable list_
- Removed highlight enchantments (uses tool tip event)
- Removed organize enchantments (uses tool tip event)
- Removed lock slots (believe it should be ok, we'll see)
- Removed stop dropping/selling rare items (allowed)
- Removed don't reset cursor between inventories (client doesn't send mouse over)
- Removed fancy warp menu (1 click=1 input)
    - _Some concern about client running text commands while being in a menu, will see what Hypixel decides on this one_
- Removed prevent enderman teleportation (client-side effect, enderman doesn't actually move on server)
- Removed enchantment lore parsing (uses tool tip event)
- Removed backpack preview (does not show empty slots anymore)
- Removed fix night vision (only client side)
- Removed hide skeleton helmet bones (doesn't block clicks)
- Removed hide players in lobby (doesn't block clicks)
- Removed show item cool downs (doesn't block clicks, only jungle axe one does rn)
- Removed hide other players' presents (doesn't block clicks)

**Comment by Minionflo** [comment]
Please add a option to activate them again

**Comment by ILikePlayingGames** [comment]
We are considering rewriting "hide players near NPCs" to be compliant but we cannot re-enable any of these features since doing so would be against Hypixel rules.

**Comment by Minionflo** [comment]
but could you add a command to enable them for people who dont care?

**Comment by Pndablob** [comment]
These features have been re-enabled upon further consideration:

**Hide Players Near NPCs (12)**:
- Does exactly as advertised. All of the code that allowed players to click through entities near NPCs has been sacked. (and the code responsible for sacking the code has also been sacked).

**Double Warp (86)**:
- This feature was not targeted by the updated mod guidelines a few months ago, and removing it in the first place was probably an over-reaction.

**Disable Empty Glass Panes (154)**:
- Like the "prevent drop" and "lock slots" features, this feature simply cancels annoying clicks in the sb menu GUI.

**Comment by ILikePlayingGames** [comment]
These features have been re-enabled in the release upon further consideration:

**Prevent movement on death** (35)

- Doesn't provide any unfair advantage

**Comment by RomanPlayer22** [comment]
Will Experimentation Table Solvers be disabled or added some kind of measure to them?
